media: assets/uploads
content:
  - name: testing
    label: Testing
    type: file
    path: _data/fields.json
    fields:
      - name: fields
        label: Fields
        type: block
        list: true
        blocks:
        - name: input
          label: Add Input field
          component: input # Assumes a 'hero' component is defined and that its type is
  - name: global
    label: Site data
    type: file
    path: _data/global.json
    fields:
      - name: siteDomain
        label: Site domain
        type: string
        description: Should be formatted like "https://domain.com". Be sure to leave off the trailing "/"
      - name: siteTitle
        label: Site title
        type: string
      - name: siteDescription
        label: Site description
        description: The fallback page description that shows when you share a link to a page without its own page description set.
      - name: siteImage
        label: Site share image
        type: image
        description: The fallback image that shows when you share a link to a page without its own share image set. Ideally should be 1200 x 630 pixels.
      - name: favicon
        label: Browser tab icon
        type: image
        description: The little icon that shows in browser tabs. 128x128px PNG works.
      - name: announcementBannerContent
        label: Announcement banner content
        type: rich-text
        description: Content to be displayed in a banner on top of webpages. Leave blank to hide the banner.
  - name: event
    label: Event details
    type: file
    path: _data/eventDetails.json
    fields:
      - name: graphic
        label: Event graphic
        type: image
      - name: title
        label: Event title
        type: string
      - name: subtitle
        label: Event subtitle
        type: string
      - name: date
        label: Event date
        type: string
      - name: location
        label: Event location
        type: rich-text
      - name: ticketInfo
        label: Ticket info
        type: rich-text
      - name: description
        label: Event description
        type: rich-text

components:
  input:
    label: Input
    type: object
    fields:
      - name: props
        label: Component props
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: label
            label: Label
            type: string
          - name: description
            label: Description
            type: string
      - name: fieldAttrs
        label: Input HTML attributes
        type: object
        fields:
          - name: type
            label: Input type
            type: string
          - name: placeholder
            label: Placeholder text
            type: string
          - name: required
            label: Required?
            type: boolean
          - name: min
            label: Minimum value
            type: number
          - name: max
            label: Maximum value
            type: number
  accordion:
    label: Accordion
    type: object
    list:
      collapsible:
        collapsed: true
        summary: "{index}: {fields.title}"
    fields:
      - name: title
        label: Question
        type: string
      - name: description
        label: Answer
        type: rich-text
      - name: isOpen
        label: Expanded
        type: boolean
        default: false
  metadata:
    label: SEO metadata
    type: object
    fields:
      - name: seoTitle
        label: SEO page title
        type: string
        description: The title of the page that shows when you share the link
      - name: seoDescription
        label: SEO description
        type: string
        description: The description of the page used for SEO purposes
      - name: seoImage
        label: Share image
        type: image
        description: The image that shows when you share the link. Ideally should be 1200 x 630 pixels.
settings:
  hide: true
  content:
    merge: true
